import FiniteCases

/-!
  # FiniteCasesExtended2 — crystal_nonsurjectivity for k ∈ [307, 665]

  359 individual cases proved by native_decide.
  Integers up to 2^1055 (~318 decimal digits).
  Generated automatically.
-/

namespace Collatz.FiniteCases

open Real Nat

theorem crystal_nonsurjectivity_307_665 (k : ℕ) (hk : k ≥ 307) (hk_le : k ≤ 665)
    (S : ℕ) (hS : S = Nat.ceil (↑k * (Real.log 3 / Real.log 2)))
    (hd : crystalModule S k > 0) :
    Nat.choose (S - 1) (k - 1) < (crystalModule S k).toNat := by
  interval_cases k
  · exact close_case 307 487 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 308 489 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 309 490 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 310 492 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 311 493 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 312 495 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 313 497 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 314 498 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 315 500 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 316 501 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 317 503 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 318 505 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 319 506 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 320 508 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 321 509 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 322 511 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 323 512 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 324 514 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 325 516 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 326 517 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 327 519 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 328 520 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 329 522 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 330 524 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 331 525 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 332 527 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 333 528 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 334 530 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 335 531 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 336 533 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 337 535 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 338 536 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 339 538 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 340 539 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 341 541 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 342 543 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 343 544 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 344 546 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 345 547 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 346 549 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 347 550 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 348 552 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 349 554 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 350 555 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 351 557 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 352 558 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 353 560 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 354 562 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 355 563 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 356 565 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 357 566 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 358 568 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 359 570 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 360 571 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 361 573 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 362 574 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 363 576 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 364 577 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 365 579 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 366 581 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 367 582 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 368 584 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 369 585 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 370 587 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 371 589 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 372 590 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 373 592 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 374 593 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 375 595 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 376 596 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 377 598 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 378 600 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 379 601 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 380 603 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 381 604 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 382 606 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 383 608 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 384 609 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 385 611 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 386 612 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 387 614 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 388 615 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 389 617 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 390 619 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 391 620 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 392 622 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 393 623 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 394 625 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 395 627 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 396 628 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 397 630 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 398 631 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 399 633 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 400 634 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 401 636 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 402 638 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 403 639 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 404 641 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 405 642 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 406 644 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 407 646 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 408 647 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 409 649 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 410 650 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 411 652 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 412 654 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 413 655 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 414 657 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 415 658 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 416 660 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 417 661 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 418 663 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 419 665 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 420 666 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 421 668 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 422 669 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 423 671 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 424 673 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 425 674 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 426 676 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 427 677 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 428 679 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 429 680 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 430 682 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 431 684 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 432 685 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 433 687 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 434 688 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 435 690 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 436 692 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 437 693 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 438 695 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 439 696 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 440 698 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 441 699 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 442 701 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 443 703 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 444 704 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 445 706 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 446 707 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 447 709 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 448 711 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 449 712 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 450 714 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 451 715 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 452 717 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 453 718 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 454 720 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 455 722 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 456 723 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 457 725 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 458 726 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 459 728 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 460 730 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 461 731 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 462 733 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 463 734 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 464 736 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 465 738 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 466 739 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 467 741 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 468 742 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 469 744 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 470 745 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 471 747 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 472 749 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 473 750 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 474 752 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 475 753 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 476 755 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 477 757 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 478 758 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 479 760 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 480 761 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 481 763 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 482 764 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 483 766 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 484 768 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 485 769 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 486 771 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 487 772 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 488 774 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 489 776 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 490 777 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 491 779 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 492 780 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 493 782 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 494 783 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 495 785 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 496 787 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 497 788 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 498 790 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 499 791 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 500 793 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 501 795 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 502 796 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 503 798 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 504 799 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 505 801 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 506 802 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 507 804 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 508 806 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 509 807 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 510 809 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 511 810 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 512 812 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 513 814 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 514 815 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 515 817 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 516 818 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 517 820 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 518 822 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 519 823 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 520 825 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 521 826 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 522 828 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 523 829 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 524 831 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 525 833 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 526 834 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 527 836 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 528 837 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 529 839 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 530 841 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 531 842 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 532 844 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 533 845 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 534 847 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 535 848 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 536 850 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 537 852 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 538 853 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 539 855 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 540 856 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 541 858 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 542 860 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 543 861 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 544 863 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 545 864 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 546 866 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 547 867 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 548 869 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 549 871 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 550 872 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 551 874 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 552 875 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 553 877 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 554 879 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 555 880 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 556 882 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 557 883 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 558 885 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 559 886 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 560 888 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 561 890 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 562 891 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 563 893 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 564 894 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 565 896 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 566 898 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 567 899 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 568 901 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 569 902 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 570 904 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 571 906 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 572 907 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 573 909 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 574 910 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 575 912 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 576 913 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 577 915 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 578 917 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 579 918 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 580 920 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 581 921 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 582 923 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 583 925 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 584 926 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 585 928 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 586 929 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 587 931 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 588 932 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 589 934 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 590 936 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 591 937 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 592 939 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 593 940 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 594 942 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 595 944 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 596 945 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 597 947 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 598 948 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 599 950 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 600 951 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 601 953 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 602 955 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 603 956 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 604 958 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 605 959 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 606 961 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 607 963 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 608 964 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 609 966 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 610 967 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 611 969 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 612 970 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 613 972 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 614 974 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 615 975 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 616 977 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 617 978 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 618 980 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 619 982 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 620 983 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 621 985 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 622 986 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 623 988 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 624 990 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 625 991 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 626 993 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 627 994 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 628 996 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 629 997 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 630 999 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 631 1001 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 632 1002 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 633 1004 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 634 1005 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 635 1007 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 636 1009 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 637 1010 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 638 1012 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 639 1013 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 640 1015 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 641 1016 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 642 1018 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 643 1020 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 644 1021 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 645 1023 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 646 1024 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 647 1026 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 648 1028 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 649 1029 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 650 1031 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 651 1032 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 652 1034 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 653 1035 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 654 1037 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 655 1039 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 656 1040 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 657 1042 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 658 1043 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 659 1045 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 660 1047 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 661 1048 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 662 1050 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 663 1051 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 664 1053 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd
  · exact close_case 665 1055 (by omega) (by omega) (by native_decide) (by native_decide) (by native_decide) S (by convert hS using 2) hd

end Collatz.FiniteCases