/-
  CorrSum Avoidance — Core Definitions
  AUTO-GENERATED by Syracuse-JEPA Pipeline Formalizer

  corrSum(A, k) = Σᵢ 3^{k-1-i} · 2^{Aᵢ}
  S(k) = ⌈k · log₂(3)⌉
  d(k) = 2^{S(k)} - 3^k
-/

namespace CorrSumAvoidance

/-- corrSum helper -/
def corrSumGo : List Nat → Nat → Nat
  | [], _ => 0
  | a :: rest, pow3 => 3 ^ pow3 * 2 ^ a + corrSumGo rest (pow3 - 1)

/-- corrSum(A, k) = Σᵢ₌₀^{k-1} 3^{k-1-i} · 2^{Aᵢ} -/
def corrSum (A : List Nat) (k : Nat) : Nat :=
  corrSumGo A (k - 1)

/-- Enumerate monotone compositions of `total` into `parts` parts ≥ `minVal` -/
def enumMonotone : Nat → Nat → Nat → List (List Nat)
  | 0, total, _ => if total == 0 then [[]] else []
  | parts + 1, total, minVal =>
    if parts == 0 then
      if total ≥ minVal then [[total]] else []
    else
      let k := parts + 1
      let maxFirst := total / k
      if maxFirst < minVal then []
      else
        ((List.range (maxFirst - minVal + 1)).map fun i =>
          let v := i + minVal
          (enumMonotone parts (total - v) v).map (v :: ·)).flatten

/-- S(k) = ⌈k · log₂(3)⌉ -/
def S_table : Nat → Nat
  | 0 => 0
  | 1 => 2
  | 2 => 4
  | 3 => 5
  | 4 => 7
  | 5 => 8
  | 6 => 10
  | 7 => 12
  | 8 => 13
  | 9 => 15
  | 10 => 16
  | 11 => 18
  | 12 => 20
  | 13 => 21
  | 14 => 23
  | 15 => 24
  | 16 => 26
  | 17 => 27
  | 18 => 29
  | 19 => 31
  | 20 => 32
  | 21 => 34
  | 22 => 35
  | 23 => 37
  | 24 => 39
  | 25 => 40
  | 26 => 42
  | 27 => 43
  | 28 => 45
  | 29 => 46
  | 30 => 48
  | 31 => 50
  | 32 => 51
  | 33 => 53
  | 34 => 54
  | 35 => 56
  | 36 => 58
  | 37 => 59
  | 38 => 61
  | 39 => 62
  | 40 => 64
  | _ => 0

/-- d(k) = 2^{S(k)} - 3^k -/
def d_val (k : Nat) : Nat :=
  2 ^ (S_table k) - 3 ^ k

/-- Check N₀ = 0: all compositions have corrSum not divisible by d -/
def checkAvoidance (k : Nat) : Bool :=
  let s := S_table k
  let d := d_val k
  if d == 0 then false
  else
    (enumMonotone k s 0).all fun A => corrSum A k % d != 0

/-- Check a specific composition is a phantom -/
def checkPhantom (A : List Nat) (k : Nat) : Bool :=
  let d := d_val k
  d != 0 && corrSum A k % d == 0

end CorrSumAvoidance
